### ISSUE TITLE
Providing trained models

### ISSUE THREAD

**Issue by shivashankarrs** [shauli-ravfogel/nullspace_projection#5]
Hi,

Thanks for the great work. Is it possible to provide the models (bias rowspaces, P_svm.num-clfs=300.npy), to reproduce results here: https://github.com/shauli-ravfogel/nullspace_projection/blob/master/notebooks/debiased_representation.ipynb

**Comment by yanaiela** [comment]
Sorry for the delay, I somehow missed this issue.
You can download the models from google storage:

`wget https://storage.googleapis.com/ai2i/nullspace/deepmoji/projections/emoji_sent_race_0.8/P_svm.num-clfs=300.npy`

(replace the name of the directory based on the classes ratio you're interested in emoji_sent_race_0.8/emoji_sent_race_0.7/...)
